version: '3.8'
services:
    checkout:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_HOST: checkout_db
            DB_DATABASE: checkout
            DB_USERNAME: admin1
            DB_PASSWORD: admin1
        command: 'php artisan serve --host=0.0.0.0 --port=8000'
        ports:
            - 8002:8000
        depends_on:
            - checkout_db

    checkout_db:
        container_name: checkout_db
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: checkout
            MYSQL_USER: admin1
            MYSQL_PASSWORD: admin1
            MYSQL_ROOT_PASSWORD: admin1
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 33069:3306
